[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "nspr",
  "at-spi2-atk",
  "cups",
  "libxkbcommon",
  "libxcomposite",
  "libxdamage",
  "libxrandr",
  "mesa",
  "alsa-lib",
  "pango",
  "cairo",
  "xorg.libX11",
  "xorg.libXcursor",
  "xorg.libXi",
  "nanum-fonts"
]

[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "playwright install chromium",
  "playwright install-deps chromium"
]
